"""add first seen col

Revision ID: 4f30801e02f0
Revises: 5bb783704d4f
Create Date: 2019-08-08 11:41:19.333346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f30801e02f0'
down_revision = '5bb783704d4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doggos', sa.Column('first_seen_listed', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doggos', 'first_seen_listed')
    # ### end Alembic commands ###
