"""first rev

Revision ID: 5bb783704d4f
Revises: 
Create Date: 2019-08-08 11:33:17.227937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bb783704d4f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doggos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('date_added', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('listing_id', sa.String(), nullable=True),
    sa.Column('breed', sa.String(), nullable=True),
    sa.Column('in_shelter_since', sa.String(), nullable=True),
    sa.Column('birthday', sa.String(), nullable=True),
    sa.Column('sex', sa.String(), nullable=True),
    sa.Column('size', sa.String(), nullable=True),
    sa.Column('age_span', sa.String(), nullable=True),
    sa.Column('featured_image_link', sa.String(), nullable=True),
    sa.Column('last_seen_listed', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('doggos')
    # ### end Alembic commands ###
